import Head from "next/head";
import Footer from "./components/footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth	">
      <body className="container mx-auto bg-white">
        {children}
        <Footer />
      </body>
    </html>
  );
}
